pipeline {
    agent any

    environment {
        APP_NAME = 'hello-world-app'
        IMAGE_NAME = "python:3.10"
    }

    stages {
        // Stage 1: Build the application
        stage('Build') {
            steps {
                echo 'Building the Hello World application...'
                
            }
        }

        // Stage 2: Test the application
        stage('Test') {
            steps {
                echo 'Running tests...'
                
                }
            }
    

        // Stage 3: Deploy the application
        stage('Deploy') {
            steps {
                echo 'Deploying the Hello World application...'
            
            }
        }
    }

   

