// pipeline {
//     agent any
//     stages {
//         stage('Checkout') {
//             steps {
//                 git 'https://github.com/PadminiPriyanka28/simple-python-pyinstaller-app.git'
//             }
//         }
//         stage('Build') {
//             steps {
//                 sh 'pip install -r requirements.txt'
//                 sh 'pyinstaller --onefile main.py'
//             }
//         }
//     }
// }


pipeline {
    agent any  // Or use a label if you have specific agents

    stages {
        stage('Install Dependencies') {
            agent {
                docker { image 'python:3.9' }
            }
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Build') {
            steps {
                sh 'pyinstaller --onefile hello.py'
            }
        }
    }
}
