// pipeline {
//     agent any
//     stages {
//         stage('Checkout') {
//             steps {
//                 git 'https://github.com/PadminiPriyanka28/simple-python-pyinstaller-app.git'
//             }
//         }
//         stage('Build') {
//             steps {
//                 sh 'pip install -r requirements.txt'
//                 sh 'pyinstaller --onefile main.py'
//             }
//         }
//     }
// }


pipeline {
    agent {
        docker {
            image 'python:3.9'
            args '-u root:root'
        }
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Build') {
            steps {
                sh 'pyinstaller --onefile hello.py'
            }
        }
    }
}
